In [1]:
import pandas as pd

In [2]:
df_path = "api_data.csv"

In [3]:
df = pd.read_csv(df_path)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57210 entries, 0 to 57209
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   57210 non-null  int64
 1   IMDbID       57210 non-null  object
 2   Title        57210 non-null  object
 3   Year         57210 non-null  object
 4   Runtime      56938 non-null  object
 5   Genre        57111 non-null  object
 6   Rated        40884 non-null  object
 7   Language     56747 non-null  object
 8   Country      57058 non-null  object
 9   Awards       32032 non-null  object
 10  Ratings      57210 non-null  object
 11  Metascore    14042 non-null  float64
 12  IMDb_Rating  57012 non-null  float64
 13  Box_Office   15188 non-null  object
dtypes: float64(2), int64(1), object(11)
memory usage: 6.1+ MB

In [5]:
df

,Unnamed: 0,IMDbID,Title,Year,Runtime,Genre,Rated,Language,Country,Awards,Ratings,Metascore,IMDb_Rating,Box_Office
0,0,tt0114709,Toy Story,1995,81 min,"Animation, Adventure, Comedy",G,English,United States,Nominated for 3 Oscars. 27 wins & 23 nominatio...,"[{'Source': 'Internet Movie Database', 'Value'...",95.0,8.3,"$223,225,679"
1,1,tt0113497,Jumanji,1995,104 min,"Adventure, Comedy, Family",PG,"English, French",United States,4 wins & 11 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",39.0,7.0,"$100,499,940"
2,2,tt0113228,Grumpier Old Men,1995,101 min,"Comedy, Romance",PG-13,"English, Italian, German",United States,2 wins & 2 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",46.0,6.6,"$71,518,503"
3,3,tt0114885,Waiting to Exhale,1995,124 min,"Comedy, Drama, Romance",R,English,United States,9 wins & 10 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",NaN,5.9,"$67,052,156"
4,4,tt0113041,Father of the Bride Part II,1995,106 min,"Comedy, Family, Romance",PG,English,United States,1 win & 2 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",49.0,6.0,"$76,594,107"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57205,57205,tt0459449,M. Kumaran S/O Mahalakshmi,2004,166 min,"Action, Drama, Sport",Not Rated,Tamil,India,2 wins & 3 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",NaN,7.2,NaN
57206,57206,tt0485486,Something Something... Unnakum Ennakum,2006,178 min,Romance,Not Rated,Tamil,India,1 win,"[{'Source': 'Internet Movie Database', 'Value'...",NaN,6.9,NaN
57207,57207,tt1606183,Boss Engira Baskaran,2010,161 min,Comedy,Not Rated,Tamil,India,3 wins & 4 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",NaN,7.2,NaN
57208,57208,tt5339432,Metamorphosis,2015,103 min,Drama,NaN,Russian,Russia,1 nomination,"[{'Source': 'Internet Movie Database', 'Value'...",NaN,6.0,NaN
57209,57209,tt1537032,Kanthaswamy,2009,190 min,"Action, Adventure, Crime",Not Rated,"Tamil, Telugu",India,1 win & 11 nominations,"[{'Source': 'Internet Movie Database', 'Value'...",NaN,5.0,NaN

In [6]:
del df["Awards"]

In [7]:
del df["Ratings"]

In [8]:
del df["Unnamed: 0"]

In [9]:
reduced = df.dropna()

In [10]:
reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5967 entries, 0 to 56717
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IMDbID       5967 non-null   object
 1   Title        5967 non-null   object
 2   Year         5967 non-null   object
 3   Runtime      5967 non-null   object
 4   Genre        5967 non-null   object
 5   Rated        5967 non-null   object
 6   Language     5967 non-null   object
 7   Country      5967 non-null   object
 8   Metascore    5967 non-null   float64
 9   IMDb_Rating  5967 non-null   float64
 10  Box_Office   5967 non-null   object
dtypes: float64(2), object(9)
memory usage: 559.4+ KB

In [11]:
reduced['Runtime'] = reduced['Runtime'].str.extract('(\d+)').astype(int)
reduced

/var/folders/zx/f3x1cdq12r37rn4kv9477k6m0000gn/T/ipykernel_45467/838872731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced['Runtime'] = reduced['Runtime'].str.extract('(\d+)').astype(int)

,IMDbID,Title,Year,Runtime,Genre,Rated,Language,Country,Metascore,IMDb_Rating,Box_Office
0,tt0114709,Toy Story,1995,81,"Animation, Adventure, Comedy",G,English,United States,95.0,8.3,"$223,225,679"
1,tt0113497,Jumanji,1995,104,"Adventure, Comedy, Family",PG,"English, French",United States,39.0,7.0,"$100,499,940"
2,tt0113228,Grumpier Old Men,1995,101,"Comedy, Romance",PG-13,"English, Italian, German",United States,46.0,6.6,"$71,518,503"
4,tt0113041,Father of the Bride Part II,1995,106,"Comedy, Family, Romance",PG,English,United States,49.0,6.0,"$76,594,107"
5,tt0113277,Heat,1995,170,"Action, Crime, Drama",R,"English, Spanish",United States,76.0,8.3,"$67,436,818"
...,...,...,...,...,...,...,...,...,...,...,...
56310,tt2249081,The Forgiven,2017,115,Thriller,R,English,United Kingdom,41.0,5.9,"$1,250,798"
56357,tt7839456,The Prayer,2018,107,Drama,PG-13,French,France,72.0,6.7,"$29,790,236"
56505,tt4823592,The Competition,2016,121,Documentary,Not Rated,French,France,69.0,7.0,"$61,271"
56651,tt1138002,Chris & Don: A Love Story,2007,90,"Documentary, Biography, Romance",Not Rated,English,United States,81.0,7.8,"$11,400"
56717,tt6101602,Madeline's Madeline,2018,93,Drama,Unrated,English,United States,78.0,6.3,"$11,640"

In [15]:
reduced['Box_Office'] = reduced['Box_Office'].str.replace("$", "")
reduced

/var/folders/zx/f3x1cdq12r37rn4kv9477k6m0000gn/T/ipykernel_45467/201547496.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  reduced['Box_Office'] = reduced['Box_Office'].str.replace("$", "")
/var/folders/zx/f3x1cdq12r37rn4kv9477k6m0000gn/T/ipykernel_45467/201547496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced['Box_Office'] = reduced['Box_Office'].str.replace("$", "")

,IMDbID,Title,Year,Runtime,Genre,Rated,Language,Country,Metascore,IMDb_Rating,Box_Office
0,tt0114709,Toy Story,1995,81,"Animation, Adventure, Comedy",G,English,United States,95.0,8.3,"223,225,679"
1,tt0113497,Jumanji,1995,104,"Adventure, Comedy, Family",PG,"English, French",United States,39.0,7.0,"100,499,940"
2,tt0113228,Grumpier Old Men,1995,101,"Comedy, Romance",PG-13,"English, Italian, German",United States,46.0,6.6,"71,518,503"
4,tt0113041,Father of the Bride Part II,1995,106,"Comedy, Family, Romance",PG,English,United States,49.0,6.0,"76,594,107"
5,tt0113277,Heat,1995,170,"Action, Crime, Drama",R,"English, Spanish",United States,76.0,8.3,"67,436,818"
...,...,...,...,...,...,...,...,...,...,...,...
56310,tt2249081,The Forgiven,2017,115,Thriller,R,English,United Kingdom,41.0,5.9,"1,250,798"
56357,tt7839456,The Prayer,2018,107,Drama,PG-13,French,France,72.0,6.7,"29,790,236"
56505,tt4823592,The Competition,2016,121,Documentary,Not Rated,French,France,69.0,7.0,"61,271"
56651,tt1138002,Chris & Don: A Love Story,2007,90,"Documentary, Biography, Romance",Not Rated,English,United States,81.0,7.8,"11,400"
56717,tt6101602,Madeline's Madeline,2018,93,Drama,Unrated,English,United States,78.0,6.3,"11,640"

In [16]:
reduced['Box_Office'] = reduced['Box_Office'].str.replace(",", "")
reduced

/var/folders/zx/f3x1cdq12r37rn4kv9477k6m0000gn/T/ipykernel_45467/2820019551.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced['Box_Office'] = reduced['Box_Office'].str.replace(",", "")

,IMDbID,Title,Year,Runtime,Genre,Rated,Language,Country,Metascore,IMDb_Rating,Box_Office
0,tt0114709,Toy Story,1995,81,"Animation, Adventure, Comedy",G,English,United States,95.0,8.3,223225679
1,tt0113497,Jumanji,1995,104,"Adventure, Comedy, Family",PG,"English, French",United States,39.0,7.0,100499940
2,tt0113228,Grumpier Old Men,1995,101,"Comedy, Romance",PG-13,"English, Italian, German",United States,46.0,6.6,71518503
4,tt0113041,Father of the Bride Part II,1995,106,"Comedy, Family, Romance",PG,English,United States,49.0,6.0,76594107
5,tt0113277,Heat,1995,170,"Action, Crime, Drama",R,"English, Spanish",United States,76.0,8.3,67436818
...,...,...,...,...,...,...,...,...,...,...,...
56310,tt2249081,The Forgiven,2017,115,Thriller,R,English,United Kingdom,41.0,5.9,1250798
56357,tt7839456,The Prayer,2018,107,Drama,PG-13,French,France,72.0,6.7,29790236
56505,tt4823592,The Competition,2016,121,Documentary,Not Rated,French,France,69.0,7.0,61271
56651,tt1138002,Chris & Don: A Love Story,2007,90,"Documentary, Biography, Romance",Not Rated,English,United States,81.0,7.8,11400
56717,tt6101602,Madeline's Madeline,2018,93,Drama,Unrated,English,United States,78.0,6.3,11640

In [17]:
reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5967 entries, 0 to 56717
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IMDbID       5967 non-null   object
 1   Title        5967 non-null   object
 2   Year         5967 non-null   object
 3   Runtime      5967 non-null   int64
 4   Genre        5967 non-null   object
 5   Rated        5967 non-null   object
 6   Language     5967 non-null   object
 7   Country      5967 non-null   object
 8   Metascore    5967 non-null   float64
 9   IMDb_Rating  5967 non-null   float64
 10  Box_Office   5967 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 559.4+ KB

In [18]:
reduced['Box_Office'] = reduced['Box_Office'].astype("int")
reduced

/var/folders/zx/f3x1cdq12r37rn4kv9477k6m0000gn/T/ipykernel_45467/402293123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced['Box_Office'] = reduced['Box_Office'].astype("int")

,IMDbID,Title,Year,Runtime,Genre,Rated,Language,Country,Metascore,IMDb_Rating,Box_Office
0,tt0114709,Toy Story,1995,81,"Animation, Adventure, Comedy",G,English,United States,95.0,8.3,223225679
1,tt0113497,Jumanji,1995,104,"Adventure, Comedy, Family",PG,"English, French",United States,39.0,7.0,100499940
2,tt0113228,Grumpier Old Men,1995,101,"Comedy, Romance",PG-13,"English, Italian, German",United States,46.0,6.6,71518503
4,tt0113041,Father of the Bride Part II,1995,106,"Comedy, Family, Romance",PG,English,United States,49.0,6.0,76594107
5,tt0113277,Heat,1995,170,"Action, Crime, Drama",R,"English, Spanish",United States,76.0,8.3,67436818
...,...,...,...,...,...,...,...,...,...,...,...
56310,tt2249081,The Forgiven,2017,115,Thriller,R,English,United Kingdom,41.0,5.9,1250798
56357,tt7839456,The Prayer,2018,107,Drama,PG-13,French,France,72.0,6.7,29790236
56505,tt4823592,The Competition,2016,121,Documentary,Not Rated,French,France,69.0,7.0,61271
56651,tt1138002,Chris & Don: A Love Story,2007,90,"Documentary, Biography, Romance",Not Rated,English,United States,81.0,7.8,11400
56717,tt6101602,Madeline's Madeline,2018,93,Drama,Unrated,English,United States,78.0,6.3,11640

In [19]:
reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5967 entries, 0 to 56717
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IMDbID       5967 non-null   object
 1   Title        5967 non-null   object
 2   Year         5967 non-null   object
 3   Runtime      5967 non-null   int64
 4   Genre        5967 non-null   object
 5   Rated        5967 non-null   object
 6   Language     5967 non-null   object
 7   Country      5967 non-null   object
 8   Metascore    5967 non-null   float64
 9   IMDb_Rating  5967 non-null   float64
 10  Box_Office   5967 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 559.4+ KB

In [21]:
reduced.to_csv("reduced_api_data.csv")